[versions]
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidDatabaseSqlcipher = "4.5.4"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
componentsResources = "1.10.1"
composeHotReload = "1.0.0"
composeMultiplatform = "1.10.1"
composeMultiplatformMediaPlayer = "1.0.53"
decompose = "3.4.0"
foundation = "1.10.1"
jbcrypt = "0.4"
junit = "4.13.2"
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotlinxSerializationJson = "1.10.0"
ktor = "3.4.0"
material3 = "1.9.0"
runtime = "1.10.1"
sqlite = "2.6.2"
sqliteJdbcVersion = "3.51.2.0"
uiToolingPreview = "1.10.1"

[libraries]
android-database-sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "androidDatabaseSqlcipher" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
compose-multiplatform-media-player = { module = "network.chaintech:compose-multiplatform-media-player", version.ref = "composeMultiplatformMediaPlayer" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
ext-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
desktop-database-sqlcipher = { module = "io.github.willena:sqlite-jdbc", version.ref = "sqliteJdbcVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-android = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-desktop = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "uiToolingPreview" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }